In [44]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
df=pd.read_csv("C:/Users/hchin/OneDrive/Desktop/Home Credit/Home Credit/application_train.csv")
df.shape

(307511, 122)

In [45]:
null_values=(df.isna().sum()/df.shape[0])*100

In [17]:
df.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='str', length=122)

In [18]:
len(df.select_dtypes(include='int').columns)

41

In [46]:
len(df.select_dtypes(include='object').columns)

16

In [20]:
len(df.select_dtypes(include='float').columns)

65

In [21]:
df['NAME_CONTRACT_TYPE'].value_counts().index[0]

'Cash loans'

In [22]:
df['AMT_INCOME_TOTAL'].median()

np.float64(147150.0)

In [23]:
df.isna().sum().sum()

np.int64(9152465)

In [41]:
for i in df.select_dtypes(include=['int','float']).columns:
  df.fillna(df[i].median(),inplace=True)
for i in df.select_dtypes(include='object').columns:
  df.fillna(df[i].value_counts().index[0],inplace=True)

In [32]:
df.isna().sum().sum()

np.int64(291334)

In [47]:
df.select_dtypes(include='object').columns

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
       'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
       'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'],
      dtype='str')

In [48]:
from sklearn.preprocessing import LabelEncoder

for i in df.select_dtypes(include='object').columns:
    df[i] = df[i].astype(str)
    le=LabelEncoder()
    le.fit(df[i])
    transformed_values=le.transform(df[i])
    df[i]=transformed_values

In [35]:
df.head()


,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
228290,364431,0,0,0,0,0,0,202500.0,1011402.0,35964.0,...,0,0,0,0,0.0,0.0,0.0,4.0,0.0,2.0
54047,162618,0,0,0,0,1,1,306000.0,675000.0,27621.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
297449,444607,0,0,0,0,1,0,135000.0,562491.0,22437.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
111027,228805,0,1,0,1,1,1,67500.0,202500.0,10125.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
257618,398120,0,0,0,0,0,0,85500.0,900000.0,26316.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN


In [36]:
df.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='str', length=122)

In [37]:
df['TARGET'].value_counts()

TARGET
0    9188
1     812
Name: count, dtype: int64

In [38]:
##model building
df=df.sample(10000)
y=df['TARGET']
x=df.drop('TARGET',axis=1)

In [39]:
y.shape,x.shape

((10000,), (10000, 121))

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(8000, 121) (2000, 121) (8000,) (2000,)


In [42]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
print(dt.predict(x_test)[0:10])
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
print(rf.predict(x_test)[0:10])


[1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [43]:
# model validation
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,dt.predict(x_test)))
print(confusion_matrix(y_test,rf.predict(x_test)))
print(accuracy_score(y_test,dt.predict(x_test)))
print(accuracy_score(y_test,rf.predict(x_test)))

[[1644  195]
 [ 137   24]]
[[1839    0]
 [ 161    0]]
0.834
0.9195
